version: '3.8'

networks:
  airflow:
    driver: bridge

services:
  postgres_airflow:
    image: postgres:13
    container_name: postgres_airflow
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5434:5432"
    volumes:
      - airflow_db:/var/lib/postgresql/data
    networks:
      - airflow

  airflow-webserver:
    image: apache/airflow:2.9.0
    container_name: airflow_webserver
    depends_on:
      - postgres_airflow
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_airflow:5432/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "b2f3d9a6d7124bb0a8de7e1a6c9f3e4c"
      _PIP_ADDITIONAL_REQUIREMENTS: "pandas sqlalchemy psycopg2-binary"
      AIRFLOW__LOGGING__BASE_LOG_FOLDER: /opt/airflow/logs
      AIRFLOW__LOGGING__REMOTE_LOGGING: 'False'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./csvs:/opt/airflow/csvs
      - ./logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: >
      bash -c "
      airflow db init &&
      airflow users create
        --username airflow
        --password airflow
        --firstname Air
        --lastname Flow
        --role Admin
        --email airflow@example.com ||
      true &&
      airflow webserver
      "
    networks:
      - airflow

  airflow-scheduler:
    image: apache/airflow:2.9.0
    container_name: airflow_scheduler
    depends_on:
      - postgres_airflow
      - airflow-webserver
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_airflow:5432/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "b2f3d9a6d7124bb0a8de7e1a6c9f3e4c"
      _PIP_ADDITIONAL_REQUIREMENTS: "pandas sqlalchemy psycopg2-binary"
      AIRFLOW__LOGGING__BASE_LOG_FOLDER: /opt/airflow/logs
      AIRFLOW__LOGGING__REMOTE_LOGGING: 'False'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./csvs:/opt/airflow/csvs
      - ./logs:/opt/airflow/logs
    command: scheduler
    networks:
      - airflow

  postgres_dw:
    image: postgres:13
    container_name: postgres_dw
    environment:
      POSTGRES_USER: dw_user
      POSTGRES_PASSWORD: dw_pass
      POSTGRES_DB: adworks_dw
    ports:
      - "5433:5432"
    volumes:
      - dw_data:/var/lib/postgresql/data
    networks:
      - airflow

volumes:
  airflow_db:
  dw_data:
